import { IsString, IsOptional, IsNotEmpty, IsUUID } from 'class-validator';

export class UploadSilaboDto {
  @IsString()
  @IsNotEmpty()
  @IsUUID()
  portfolioId: string; // The ID of the portfolio this silabo belongs to

  @IsString()
  @IsOptional()
  version?: string;

  // Note: There is no 'contentUrl' here because the file itself is being uploaded.
  // The 'contentUrl' will be generated by Cloudinary and saved to the database by the service.
}
